# Generated by Django 3.2.8 on 2021-10-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_post_main_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('post', models.ManyToManyField(blank=True, to='instagram.Post')),
            ],
        ),
    ]
